################################################################################
#1.Setup

### Restart R
#.rs.restartR()

### Start with a clean environment by removing objects in workspace
rm(list=ls())

### Setting work directory
working_directory <- base::setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
#working_directory <- base::setwd(".")

### Load Rdata
Rdata_files <- list.files(path = working_directory, pattern = "*.RData", full.names = T)

if ( length(Rdata_files) >0) {
  invisible(lapply(Rdata_files,load,.GlobalEnv))
} else {
  paste(c(".RData files", "do not exist"), collapse = " ")
}

### Install required packages
source("./1.setup/requirements.R")

### helper/customized functions
source("./1.setup/helperfuns_read_excel_sheets.R")
source("./1.setup/helperfuns_gt_summary_themes.R")
source("./1.setup/helperfuns_table_summary_categorical.R")
source("./1.setup/helperfuns_ggplot_themes.R")

################################################################################

### Load data 
source("./2.data_processing/load_data_local.R")

### Load recode file
source("./2.data_processing/load_recode_file.R")

### Data cleaning
source("./2.data_processing/cleaning_hararge_hdss.R")
source("./2.data_processing/cleaning_ouagadougou_hdss.R")
source("./2.data_processing/cleaning_nuhdss.R")
source("./2.data_processing/cleaning_meiru.R")
source("./2.data_processing/cleaning_iganga_hdss.R")
source("./2.data_processing/cleaning_niakhar_hdss.R")
source("./2.data_processing/merge_data.R")
source("./2.data_processing/merge_data_final.R")

### Select variables for descriptive and inferential analysis
source("./2.data_processing/analysis_data.R")

### Descriptive and Inferential stats
source("./2.data_processing/descriptive_inferential_stats.R")

### Save stats output
source("./2.data_processing/save_descriptive_inferential_output.R")

################################################################################

# 3.Scan report 
## Generate Scan Report in WHITE RABBIT using csv "VA_INSPIRE_merged_final.csv" generated in data_processing step
## Retrieve "VA_INSPIRE_merged_final.csv" saved in output folder
## Before running the scan report, set working directory to ".3scan_report" folder

################################################################################

#4.Source code list
## Create a SOURCE CODE LIST from either SCAN Report Generated or using your own generated descriptive output

################################################################################

#5.Usagi Concept
## Source code list are loaded into USAGI to map source codes into the OMOP Vocabulary (standard terminologies)
## Export final map generated by USAGI into the OMOP Vocabulary’s SOURCE_TO_CONCEPT_MAP and USAGI MAPPING CONCEPT LIST

## Load saved Usagi Vocabulary Mapping file
source("./5.usagi_concept/load_usagi_mapping_local.R")

################################################################################

#6.Mapping Source to CDM
## Open scanned results from WHITE RABBIT into RABBIT-IN-A-HAT; interface displays source tables and CDM tables
## Connect source tables to CDM tables where the source table provides information for that corresponding CDM table
## For each source table to CDM table connection, further define the connection with source column to CDM column detail
## Save Rabbit-In-a-Hat work and export to a MS Word document.
## Rabbit-In-a-Hat generates documentation for the ETL process it does not generate code to create an ETL

################################################################################

#7.ETL-TO-OMOP
## First Create a database in postgres named "va_inspire"

## Connecting to local database using DBI package

#file.edit("~/.Renviron") store password credentials for postgres in .Renviron and retrieve with Sys.getenv()
#usethis::edit_r_environ()
#restart R

database_name <- "va_inspire"

con <- dbConnect(drv = RPostgres::Postgres(),
                 dbname = database_name, 
                 host = 'localhost', 
                 port = 5432, 
                 user = 'postgres',
                 password = Sys.getenv("postgres_password")
                 #password = rstudioapi::askForPassword("Database password")
                 )

print(con)
#DBI::dbDisconnect(con)

list_va_hdss_raw <- as.character(unique(df_final$site_name))

list_va_hdss <- list_va_hdss_raw[!list_va_hdss_raw %in% c(0)]

## Create OMOP-CDM Schemas for individual studies, single vocabulary and list all schemas
### Schemas are created in lower case letters. So make site_name column is in lower case in the data
source("./7.etl_to_omop/create_cdm_vocab_results_schema.R")

## List all schemas after each study schema have been created 
list_all_schemas_cdm <- dbGetQuery(con, "SELECT schema_name FROM information_schema.schemata") #output is df

## List tables based on final dataset version adding vocabulary schema
list_tables_va_hdss <- paste(c(paste0(list_va_hdss, "_cdm"), "vocabulary"))

## List all schemas with changing final dataset version
list_all_schemas_va_hdss_cdm <- list_all_schemas_cdm %>%
  dplyr::filter(schema_name %in% list_tables_va_hdss)

## create OMOPCDM_5.4_ddl tables, Primary key, foreign keys and indexing
source("./7.etl_to_omop/create_cdm_tables_rpackage.R")

## Loading vocabularies in vocabulary schema

### using back slash as we are utilizing sql statements to load athena vocabs and INSPIRE vocabs from csv files
vocab_folder_path <- glue::glue("D:\\APHRC\\OMOP-CDM\\Usagi and Vocabulary\\vocabulary_download_v5_1757485884122")


empty_vocab_tables <- FALSE #TRUE to empty and load/reload vocabularies, FALSE to do nothing

if (empty_vocab_tables) {
  
  source("./7.etl_to_omop/empty_omop_vocabs.R")
  
  #Load ATHENA vocabs from CSV
  source("./7.etl_to_omop/load_omop_vocabs.R")
}

## Transforming data from Staging and loading to OMOP-CDM

### location table
source("./7.etl_to_omop/location_va_to_omop.R")

### Caresite table
source("./7.etl_to_omop/caresite_va_to_omop.R")

### Provider table
source("./7.etl_to_omop/provider_va_to_omop.R")

### Person table
source("./7.etl_to_omop/person_va_to_omop.R")

### Visit occurrence table
source("./7.etl_to_omop/visit_occurrence_va_to_omop.R")

### Visit detail table
source("./7.etl_to_omop/visit_detail_va_to_omop.R")

### Observation period table
source("./7.etl_to_omop/observation_period_va_to_omop.R")

### Observation table
source("./7.etl_to_omop/observation_va_to_omop.R")

### Death table
source("./7.etl_to_omop/death_va_to_omop.R")

### CDM Source table
source("./7.etl_to_omop/cdm_source_va_to_omop.R")

### Disconnecting from database
DBI::dbDisconnect(con)

################################################################################

#8.Data Quality Dashboard
source("./8.dqd/data_quality_dashboard.R")

#INSPECT LOGS

ParallelLogger::launchLogViewer(
  logFileName = base::file.path(base::file.path(DQD_Dir, "nuhdss_cdm"), 
                                paste0("log_DqDashboard_",cdm_source_cdm_table[["nuhdss_cdm"]]$cdm_source_abbreviation, ".txt")
                                )
  )

ParallelLogger::launchLogViewer(
  logFileName = base::file.path(base::file.path(DQD_Dir, "meiru_cdm"),  
                                paste0("log_DqDashboard_",cdm_source_cdm_table[["meiru_cdm"]]$cdm_source_abbreviation, ".txt"))
  )

#VIEW RESULTS
#Launching Dashboard as Shiny App
DataQualityDashboard::viewDqDashboard(base::file.path(base::file.path(DQD_Dir, "niakhar_hdss_cdm"), "niakhar_hdss_cdm_results.json"))

DataQualityDashboard::viewDqDashboard(base::file.path(base::file.path(DQD_Dir, "ouagadougou_hdss_cdm"), "ouagadougou_hdss_cdm_results.json"))

DataQualityDashboard::viewDqDashboard(base::file.path(base::file.path(DQD_Dir, "nuhdss_cdm"), "nuhdss_cdm_results.json"))

DataQualityDashboard::viewDqDashboard(base::file.path(base::file.path(DQD_Dir, "meiru_cdm"), "meiru_cdm_results.json"))

DataQualityDashboard::viewDqDashboard(base::file.path(base::file.path(DQD_Dir, "igangamayuge_hdss_cdm"), "igangamayuge_hdss_cdm_results.json"))

DataQualityDashboard::viewDqDashboard(base::file.path(base::file.path(DQD_Dir, "hararghe_hdss_cdm"), "hararghe_hdss_cdm_results.json"))


################################################################################

#9.Achilles Characterization
source("./9.achilles_results/achilles_analysis.R")

################################################################################

#10.OMOP Analysis
#summary of records in OMOP-tables
source("./10.omop_analysis/summary_OMOP_records.R")

#Connecting to local database using connection object
con <- dbConnect(drv = RPostgres::Postgres(),
                 dbname = database_name, 
                 host = 'localhost', 
                 port = 5432, 
                 user = 'postgres',
                 password = Sys.getenv("postgres_password")
                 #password = rstudioapi::askForPassword("Database password")
                 )
print(con)

vocabulary_schema_name <- "vocabulary"

#Loading and saving vocabulary schema (concept table) in Postgres to environment
source("./10.omop_analysis/read_vocabulary_schema_concept_table.R")
DBI::dbDisconnect(con)

#summary of vocabs in OMOP-tables
source("./10.omop_analysis/summary_OMOP_vocabs.R")
source("./10.omop_analysis/summary_OMOP_vocabs_study.R")

# OMOP-CDM Sketch
## Since we have one vocabulary schema, we will be creating a cdm_reference object from tables rather than from the local
## database (cdmFromCon)
source("./10.omop_analysis/cdm_reference_omop_sketch.R")

## Once we have the cdm_reference object we can start characterising it
## create a snapshot of our database. 
## This allows us to track when the analysis has been conducted and capture details about CDM version or the data release.
source("./10.omop_analysis/snapshot_omop_sketch.R")

## Once we have collected the snapshot information, we can characterise the person table
source("./10.omop_analysis/person_omop_sketch.R")

## Characterise the observation period
source("./10.omop_analysis/observation_period_omop_sketch.R")

## Characterise the clinical tables
## "visit_occurrence", "visit_detail", "condition_occurrence", "drug_exposure", "procedure_occurrence", "device_exposure"
## "measurement", "observation", "death", "note", "specimen", "payer_plan_period", "drug_era", "dose_era", "condition_era"
source("./10.omop_analysis/clinical_tables_omop_sketch.R")

## Characterise concepts in the clinical tables
top_concepts <- 15
source("./10.omop_analysis/concepts_overall_clinical_tables_omop_sketch.R")
source("./10.omop_analysis/concepts_overall_gender_clinical_tables_omop_sketch.R")
source("./10.omop_analysis/concepts_overall_agegroup_clinical_tables_omop_sketch.R")
source("./10.omop_analysis/concepts_yearly_clinical_tables_omop_sketch.R")

## Explore trends over time for death table
source("./10.omop_analysis/death_gender_trend_omop_sketch.R")
source("./10.omop_analysis/death_agegroup_trend_omop_sketch.R")

################################################################################

#11. Atlas Analysis
## Installation and Configuration Guide: WSL, Docker, OHDSI Broadsea, PgAdmin Container, and ATLAS WebAPI


################################################################################

## Save workspace at the end without working directory path

save(list = ls(all.names = TRUE)[!ls(all.names = TRUE) %in% c("working_directory", "mainDir", "data_Dir", "output_Dir"
                                                              ,"Rdata_files", "executeDDL_Error_Dir", "Achilles_Analysis_Dir"
                                                              , "DQD_Dir", "OMOPSketch_Dir", "cdm_reference", "con"
                                                              , "cd_dqd", "cd_achilles"
                                                              )],
     file = "gbd_analysis.RData",
     envir = .GlobalEnv #parent.frame()
     )

################################################################################

## Run all files in Rstudio
source("main.R")

################################################################################

